# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more info rmation see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy-prod

on: workflow_dispatch

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: deploy-web-prod
        run: |
             sudo mkdir -p /tmp/builds/ng-award/${{github.sha}}
             sudo aws s3 cp s3://arachnomesh-build/award/ng-award/${{github.sha}}/ng-award.tgz /tmp/builds/ng-award/${{github.sha}}/ 
             ssh -i ~/.ssh/arach-test-mumbai.pem ec2-user@13.234.68.166 'sudo mkdir -p /tmp/ng-award/'
             sudo scp -i ~/.ssh/arach-test-mumbai.pem /tmp/builds/ng-award/${{github.sha}}/ng-award.tgz ec2-user@13.234.68.166:/tmp/ng-award/
             ssh -i ~/.ssh/arach-test-mumbai.pem ec2-user@13.234.68.166 'sudo rm -rf /var/www/ng-award.bak/'
             ssh -i ~/.ssh/arach-test-mumbai.pem ec2-user@13.234.68.166 'sudo mv /var/www/ng-award/ /var/www/ng-award.bak/'
             ssh -i ~/.ssh/arach-test-mumbai.pem ec2-user@13.234.68.166 'sudo mkdir /var/www/ng-award/; sudo tar -xzf /tmp/ng-award/ng-award.tgz -C /var/www/ng-award/'
             sudo rm -rf /tmp/builds/ng-award/${{github.sha}}
      - name: deploy-server-prod
        run: |
             sudo mkdir -p /tmp/builds/award-server.test/${{github.sha}}
             sudo aws s3 cp s3://arachnomesh-build/award/award-server/${{github.sha}}/award-server.tgz /tmp/builds/award-server.test/${{github.sha}}/ 
             ssh -i ~/.ssh/arach-test-mumbai.pem ec2-user@13.234.68.166 'sudo mkdir -p /tmp/award-server.test/'
             sudo scp -i ~/.ssh/arach-test-mumbai.pem /tmp/builds/award-server.test/${{github.sha}}/award-server.tgz ec2-user@13.234.68.166:/tmp/award-server.test/
             ssh -i ~/.ssh/arach-test-mumbai.pem ec2-user@13.234.68.166 'sudo rm -rf /opt/node_apps/award-server.bak'
             ssh -i ~/.ssh/arach-test-mumbai.pem ec2-user@13.234.68.166 'sudo mv /opt/node_apps/award-server /opt/node_apps/award-server.bak || true'
             ssh -i ~/.ssh/arach-test-mumbai.pem ec2-user@13.234.68.166 'sudo mkdir /opt/node_apps/award-server; tar -xzf /tmp/award-server.test/award-server.tgz -C /opt/node_apps/award-server/'
             ssh -i ~/.ssh/arach-test-mumbai.pem ec2-user@13.234.68.166 'cd /opt/node_apps/award-server; npm install;'
             ssh -i ~/.ssh/arach-test-mumbai.pem ec2-user@13.234.68.166 'pm2 restart award-server;'
             sudo rm -rf /tmp/builds/award-server.test/${{github.sha}}
      - name: deploy-ngweb-prod
        run: |
             sudo mkdir -p /tmp/builds/award-prod/${{github.sha}}
             sudo aws s3 cp s3://arachnomesh-build/award/award-admin/${{github.sha}}/award-prod.tgz /tmp/builds/award-prod/${{github.sha}}/ 
             ssh -i ~/.ssh/arach-test-mumbai.pem ec2-user@13.234.68.166 'mkdir -p /tmp/award-prod/'
             sudo scp -i ~/.ssh/arach-test-mumbai.pem /tmp/builds/award-prod/${{github.sha}}/award-prod.tgz ec2-user@13.234.68.166:/tmp/award-prod/
             ssh -i ~/.ssh/arach-test-mumbai.pem ec2-user@13.234.68.166 'sudo rm -rf /var/www/award-prod.bak/'
             ssh -i ~/.ssh/arach-test-mumbai.pem ec2-user@13.234.68.166 'sudo mv /var/www/award-prod/ /var/www/award-prod.bak/'
             ssh -i ~/.ssh/arach-test-mumbai.pem ec2-user@13.234.68.166 'sudo mkdir /var/www/award-prod/; sudo tar -xzf /tmp/award-prod/award-prod.tgz -C /var/www/award-prod/'
             sudo rm -rf /tmp/builds/award-prod/${{github.sha}}
#       - name: deploy-static-web-prod
#         run: |
#              cd web/
#              ssh -i ~/.ssh/arach-prod-mumbai.pem ec2-user@13.234.68.166 'sudo rm -rf /var/www/award-frontend.bak || true'
#              ssh -i ~/.ssh/arach-prod-mumbai.pem ec2-user@13.234.68.166 'sudo mv /var/www/award-frontend /var/www/award-frontend.bak || true ; mkdir -p /var/www/award-frontend'
#              sudo scp -r -i ~/.ssh/arach-prod-mumbai.pem ./* ec2-user@13.234.68.166:/var/www/award-frontend
